# Generated by Django 5.1.4 on 2025-09-18 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_hours', models.FloatField()),
                ('total_distance', models.FloatField(blank=True, null=True)),
                ('estimated_driving_time', models.FloatField(blank=True, null=True)),
                ('total_duty_time', models.FloatField(blank=True, null=True)),
                ('is_compliant', models.BooleanField(default=True)),
                ('requires_multi_day', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RouteStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.IntegerField()),
                ('instruction', models.TextField()),
                ('distance_meters', models.FloatField()),
                ('duration_seconds', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='routes.route')),
            ],
            options={
                'ordering': ['step_order'],
            },
        ),
    ]
