# Generated by Django 5.1.4 on 2025-09-18 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('driver_name', models.CharField(default='Driver', max_length=100)),
                ('co_driver_name', models.CharField(blank=True, max_length=100)),
                ('vehicle_number', models.CharField(default='001', max_length=50)),
                ('carrier_name', models.CharField(default='Carrier', max_length=255)),
                ('total_miles', models.IntegerField(default=0)),
                ('shipping_document', models.CharField(blank=True, max_length=100)),
                ('off_duty_hours', models.FloatField(default=0)),
                ('sleeper_berth_hours', models.FloatField(default=0)),
                ('driving_hours', models.FloatField(default=0)),
                ('on_duty_hours', models.FloatField(default=0)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='routes.route')),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_status', models.CharField(choices=[('off_duty', 'Off Duty'), ('sleeper_berth', 'Sleeper Berth'), ('driving', 'Driving'), ('on_duty_not_driving', 'On Duty (Not Driving)')], max_length=25)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('total_hours', models.FloatField()),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='eld_logs.dailylog')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
